### ISSUE TITLE
Antag playtime requirements

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v-rebase#192]
## Description
As discussed, some antags will be locked behind playtime (NOT whitelist), instead of being available right when you first join.

However, currently only the nukie commander and medic have a requirement set. Proper times will still need be be created for all other antags.

#191 will also bring whitelist locking for antags we deem HRP (at this time only the nukie commander)

**Comment by FluffiestFloof** [comment]
Was 'fixed' in #206 technically
