### ISSUE TITLE
pebble issues and fire axe issuses

### ISSUE THREAD

**Issue by snowywinters** [DeltaV-Station/Delta-v-rebase#215]
in pebble mysta does not have there suit in there room and atmos does not have a atmos hardsuit in there room
and the fire axe is a little op
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/c704c099-4393-4e74-a6f7-a7073b5b170d)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/55ce0ec4-26dd-447e-a8ff-3b8e83738bb0)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/0e46d6e6-727b-489f-b210-4a27a741588f)

**Comment by DebugOk** [comment]
2 issues in one issue, resolved via #218
