### ISSUE TITLE
kettle and re machine

### ISSUE THREAD

**Issue by snowywinters** [DeltaV-Station/Delta-v-rebase#219]
the map kettle has no prober for epi and in pebble ce has no rped in there locker dont know if thats a issue or not
the reverse engineering machine scanner can not be upgraded so it takes forver for any thing to be reverse engineered 
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/9eae94ba-a2a4-42fd-9a5f-4edb7e1f9e6e)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/889e0659-2505-4191-97ad-86edd3085923)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/5eb60bb0-b403-4fb4-9fd5-296c01339714)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/134970424/9daedb55-81a3-4aa0-bfa9-2aef9a4f8351)

**Comment by DebugOk** [comment]
Kettle isn't our map
