### ISSUE TITLE
tortuga has invalid prototype name

### ISSUE THREAD

**Issue by Carolyn3114** [DeltaV-Station/Delta-v-rebase#222]
## Description

Tortuga has "ClothingHeadHoodMystic" in the YML file, which is an item that doesn't exist, causes tests and loading to fail
should instead be "ClothingHeadHoodMysta"

**Reproduction**

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/136143032/0404bc29-1c5d-4645-a915-e091400161cc)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/136143032/f0258662-5e9b-4551-ad10-d277b5979abe)
**Additional context**

caused by https://github.com/DeltaV-Station/Delta-v-rebase/pull/213

**Comment by IamVelcroboy** [comment]
This can be closed

**Comment by DEATHB4DEFEAT** [comment]
> This can be closed
