### ISSUE TITLE
missing textures for mail

### ISSUE THREAD

**Issue by Carolyn3114** [DeltaV-Station/Delta-v-rebase#238]
## Description

**Reproduction**

use mail, I suppose 

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/136143032/ce985787-b889-490e-93a4-9b272da8844b)
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/136143032/7c3123c8-e0a5-43c3-af66-447ca907330f)

**Additional context**

**Comment by DebugOk** [comment]
I could've sworn I fixed that

**Comment by DebugOk** [comment]
What jobs does this happen on?

**Comment by FluffiestFloof** [comment]
I've seen it error on "MailCarrier"
![ss (2023-10-23 at 10 36 15)](https://github.com/DeltaV-Station/Delta-v-rebase/assets/9823203/47636d4e-168b-44ad-9db2-99ca21b1fc7a)

**Comment by DebugOk** [comment]
If I had to guess its because its trying to check for our custom jobs in the hardcoded (yuck) rsi

**Comment by DebugOk** [comment]
Thats exactly what it turned out to be, oh boy thats gonna be fun to fix

**Comment by DebugOk** [comment]
Resolved by #258

**Comment by DebugOk** [comment]
Assuming this is resolved because I haven't seen anyone mention it since
