### ISSUE TITLE
Tortuga has 4 Logistic Officers locker instead of normal cargo tech lockers

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v-rebase#246]
## Description

**Reproduction**

They should only get 1 logistic officer locker.

**Screenshots**

![ss+(2023-10-23+at+09 39 05)](https://github.com/DeltaV-Station/Delta-v-rebase/assets/9823203/5e39daf5-9f45-44e7-bc39-d1b730e0c405)

**Additional context**

This means 4 traitor objectives that are the same.

**Comment by Colin-Tel** [comment]
There are no cargo tech lockers but that's just me playing semantics :)
