### ISSUE TITLE
Tortuga lacks lockers with hardsuits

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v-rebase#251]
## Description

Currently they only get filled lockers without hardsuits.
This applies to HoS, CE, Engineering, CMO, and probably more.

**Reproduction**

**Screenshots**

![ss+(2023-10-23+at+10 04 52)](https://github.com/DeltaV-Station/Delta-v-rebase/assets/9823203/827a7274-9dff-482b-9932-298b2ef253fb)

**Additional context**

Should give them "LockerEngineerFilledHardsuit" or the separate hardsuit locker.

**Comment by Colin-Tel** [comment]
Tortuga also has:
- multiple Logistics Officers lockers in the cargo breakroom.
- no hardsuits for other heads

**Comment by IamVelcroboy** [comment]
I know I replaced some of the head's lockers. I must have gotten distracted before I finished.
