### ISSUE TITLE
bird people can't be stripped

### ISSUE THREAD

**Issue by Carolyn3114** [DeltaV-Station/Delta-v-rebase#256]
## Description

bird people can't be stripped 

**Reproduction**

try to search a bird person 

**Screenshots**

**Additional context**

**Comment by FluffiestFloof** [comment]
That's one hell of an issue

**Comment by Carolyn3114** [comment]
yeah it's pretty damn annoying

**Comment by DebugOk** [comment]
@evilexecutive Did you not give them strippable :clueless:
