### ISSUE TITLE
Some mail decals display errors

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v-rebase#257]
## Description

Some of the icons for mail display these red errors instead of the job icons.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/113523727/1335fb30-6e42-448d-8e6e-ef2b13a4b54b)

**Additional context**

**Comment by FluffiestFloof** [comment]
Dupe of #238

**Comment by Colin-Tel** [comment]
my mistake lol
