### ISSUE TITLE
Whitelist needed above 30 players

### ISSUE THREAD

**Issue by luringens** [DeltaV-Station/Delta-v-rebase#259]
## Description
Seeing reports in Discord that anyone trying to join when theres more than 30 people and dont have whitelist, get a message that they cant join without a whitelist when theres 30 or more players. This matches behaviour on wizden's MRP server, where whitelist requirement is waived on lowpop.

**Reproduction**
Join withiut whitelist on periapsis with more than 30 players.

**Screenshots**
N/A

**Additional context**

https://discord.com/channels/968983104247185448/968983104951836742/1166110920758542388

https://discord.com/channels/968983104247185448/968983104662409244/1166113111820992604

**Comment by DebugOk** [comment]
Working as intended
